bump bitcoin-0.30 and miniscript-10.0
LedgerHQ/app-bitcoin-new pull request #183
Opened 2023-07-11 09:33 UTC by edouardparis

tests are failing

2023-07-11 13:11 UTC, edouardparis commented
I want the code to look like exactly like `bitcoin::psbt::serialize` module in order to reduce risk of errors, also rust-bitcoin psbt module exposes publicly only a few methods for few types. In order to have the PSBTv2 transition I needed to have access to a very low level of the PSBT mapping.

2023-07-11 13:13 UTC, darosior commented
Oh, gotcha. I overlooked the v2 part.

2023-07-17 09:02 UTC, bigspider requested changes
Thank you!
Only commented on a couple of nits.

2023-07-17 09:02 UTC, bigspider commented on bitcoin_client_rs/tests/client.rs
> +
There's identical code in lines 362:395, perhaps it can be in a function?
Even an inner function might do.

2023-07-18 08:26 UTC, bigspider approved these changes

2023-07-18 08:30 UTC, merged